config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts
  get 'public/home'
  root to: "public#home"
  resources :tags
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :body
    belongs_to :user
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings, dependent: :destroy

    def tag_list
        self.tags.collect do |tag|
            tag.name
        end.join(", ")
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :posts, through: :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order('created_at DESC')
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(user: current_user))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end
    def show
        @tag = Tag.find(params[:id])
        @tags = Tag.all 
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lobito.cl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'shared/header' %>
      <div class="container">
        <%= yield %>
      <%= render 'shared/footer' %>
      </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list, class: "input mt-3" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Post", class: "btn btn-info mt-3" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<br>
<% @posts.each do |post| %>

  <div class="card" style="width: 75%">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= sanitize post.body.to_s.slice(34..114) + "..." %></p>
      <a href=""><%= link_to 'Show', post, class: "btn btn-info" %></a>
    </div>
  </div>


<br>
<% end %>

<br>
<%= link_to 'New Post', new_post_path, class: "btn btn-dark" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: "btn btn-dark mt-3" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2><%= @post.title %></h2>
  <p><%= @post.body %></p>
  <p>Tags:
    <% @post.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag), class: "btn btn-sm btn-outline-light" %>
    <% end %>
  </p>
</div>


<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %> 
<%= link_to 'Destroy', @post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"  %>
<%= link_to 'Back', posts_path, class: "btn btn-dark" %>

app/views/shared/_footer.html.erb
<footer class="py-3 my-4">
    <ul class="nav justify-content-center pb-3 mb-3">
      <li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link px-2 text-white-50" %></li>
      <li class="nav-item"><%= link_to 'Posts', posts_path, class: "nav-link px-2 text-white-50" %></li>
      <li class="nav-item"><%= link_to 'Users', posts_path, class: "nav-link px-2 text-white-50" %></li>
      <li class="nav-item"><%= link_to 'FAQs', posts_path, class: "nav-link px-2 text-white-50" %></li>
      <li class="nav-item"><%= link_to 'About', posts_path, class: "nav-link px-2 text-white-50" %></li>
    </ul>
    <hr>
    <p class="text-center text-white-50">© 2021 Lobito.cl</p>
</footer>

app/views/shared/_header.html.erb
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to 'Home', root_path, class: "nav-link px-2 link-dark" %></li>
        <li><%= link_to 'Posts', posts_path, class: "nav-link px-2 link-dark" %></li>
        <li><%= link_to 'Tags',  tags_path, class: "nav-link px-2 link-dark" %></li>
        <li><%= link_to 'FAQs', posts_path, class: "nav-link px-2 link-dark" %></li>
        <li><%= link_to 'About', posts_path, class: "nav-link px-2 link-dark" %></li>
      </ul>

      <div class="col-md-3 text-end">
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-dark" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-dark me-2" %>
        <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-dark" %>
      <% end %>
      </div>
    </header>
</div>

app/views/tags/index.html.erb
<h1 class="text-white">Tags</h1>
<br>
<% @tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: "btn btn-outline-light" %>
<% end %>

app/views/tags/show.html.erb
<h1>Posts con la etiqueta "<%= @tag.name %>"</h1>
<br>
<ul>
    <% @tag.posts.each do |post| %>
        <li><%= link_to post.title, post_path(post) %></li>
        <%= sanitize post.body.to_s.slice(34..134) + "..." %>
    <% end %>
</ul>



<h2 class="text-muted">Todas las etiquetas</h2>

<% @tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag), class: "btn btn-outline-light me-2" %>
<% end %>